{{ if and .Values.prometheusRules.enabled ( ne .Values.environment "ci" ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
{{ toYaml .Values.prometheusRules.labels | indent 4 }}
  name: {{ .Release.Name }}
spec:
  groups:
  - name: {{ .Release.Name }}.rules
    rules:
    - alert: ScanStallShort
      annotations:
        message: 'Scanner got stuck for more than 10 minutes at block https://{{`{{ $labels.network }}`}}.subscan.io/block/{{`{{ printf "polkadot_watcher_tx_scan_height{instance=''%s''}" $labels.instance | query | first | value | printf "%.0f" }}`}} | Please check the {{`{{ $labels.namespace }}`}}/{{`{{ $labels.service }}`}} service'
      expr: increase(polkadot_watcher_tx_scan_height[10m]) == 0
      for: 10m
      labels:
        severity: warning
        origin: {{ .Values.prometheusRules.origin }}
    - alert: ScanStallLong
      annotations:
        message: 'Scanner got stuck for more than 20 minutes at block https://{{`{{ $labels.network }}`}}.subscan.io/block/{{`{{ printf "polkadot_watcher_tx_scan_height{instance=''%s''}" $labels.instance | query | first | value | printf "%.0f" }}`}} | Please check the {{`{{ $labels.namespace }}`}}/{{`{{ $labels.service }}`}} service'
      expr: increase(polkadot_watcher_tx_scan_height[10m]) == 0
      for: 20m
      labels:
        severity: critical
        origin: {{ .Values.prometheusRules.origin }}    
{{ end }}
