{{ if .Values.restarter.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-pod-restarter
spec:
  schedule: {{ .Values.restarter.schedule | quote }}
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-pod-restarter
          containers:
          - name: {{ .Release.Name }}-pod-restarter
            image: {{ .Values.restarter.image.repo }}:{{ .Values.restarter.image.tag }}
            args:
            - /scripts/restart_pods.sh
            - {{ .Release.Name }}
            - deployment
          restartPolicy: Never

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pod-restarter

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-pod-restarter
rules:
- apiGroups: ["apps"]
  verbs:
  - "get"
  resources:
  - "deployments"
- apiGroups: ["apps"]
  verbs:
  - "get"
  - "patch"
  resources:
  - "deployments/scale"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-pod-restarter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-pod-restarter
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pod-restarter


{{ end }}