endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
matrixbot:
  endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  strategy: "Default"
subscriber:
  modules:
    transferEventScanner:
      enabled: true
      #startFromBlock: 10527640 
      sent: true
      received: true
      dataDir: "./data"
      scanIntervalMillis: 300000
      retriesBeforeLeave: 5
      delayBeforeRetryMillis: 5000
  subscriptionsFromGit: #optional
    enabled: false
    targets:
    - platform: GitLab
      private:
        enabled: true
        apiToken: xxx
      network: kusama
      url: https://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main     
  subscriptions: #optional
  - name: faucet
    address: Edyfdyoi4KJVdXUJ3SU3nuZYMpg13HHa1SWYtPDCV8UPdxy 
  - name: myAddress
    address: GaK38GT7LmgCpRSTRdDC2LeiMaV9TJmx8NmQcb9L3cJ3fyX   
    transferEventScanner:
      received: false 