endpoint: "wss://kusama-rpc.polkadot.io/"
port: 3000
logLevel: info
matrixbot:
  endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
subscriber:
  modules:
    transferEvent:
      enabled: true
      sent: true
      received: true
    balanceChange:
      enabled: true
    transferExtrinsic:
      enabled: false
  subscriptions:
  - name: faucet
    address: Edyfdyoi4KJVdXUJ3SU3nuZYMpg13HHa1SWYtPDCV8UPdxy 
  - name: faucet2
    address: Cb2QccEAM38pjwmcHHTTuTukUobTHwhakKH4kBo4k8Vur8o   
    balanceChange:
      received: false 