environment: production

image:
  repo: web3f/polkadot-watcher-transaction
  tag: v0.4.6

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  matrixbot:
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
    strategy: "NoDuplicates"
    noDuplicatesWindow: 5000
  subscriber:
    modules:
      transferEvent:
        enabled: true
        sent: true
        received: true
      balanceChange:
        enabled: true
      transferExtrinsic:
        enabled: false
    subscriptions: 
    - name: faucet
      address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk 

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    cpu: "600m"
    memory: "500Mi"
