environment: production

image:
  repo: web3f/polkadot-watcher-transaction
  tag: v0.5.1

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  matrixbot:
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  subscriber:
    modules:
      transferEventScanner:
        enabled: true
        sent: true
        received: true
        dataDir: "/app/data"
        scanIntervalMillis: 300000 #5 minutes
        retriesBeforeLeave: 5
        delayBeforeRetryMillis: 5000
    subscriptions: 
    - name: faucet
      address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk 

prometheusRules:
  enabled: true
  labels:
    app: w3f
  origin: clusterName
  network: polkadot # polkadot | kusama

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    cpu: "600m"
    memory: "500Mi"
