image:
  repo: web3f/polkadot-watcher-transaction

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  environment: production
  matrixbot:
    enabled: true
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  subscriber:
    modules:
      balanceBelowThreshold:
        enabled: true
        threshold: 10
      transferEventScanner:
        enabled: true
        sent: true
        received: true
        dataDir: "/app/data"
        scanIntervalMillis: 300000
        retriesBeforeLeave: 5
        delayBeforeRetryMillis: 5000
    subscriptionsFromGit:
      enabled: false
      targets:
        - platform: GitLab
          private:
            enabled: true
            apiToken: xxx
          network: kusama
          url: https://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main
    subscriptions:
      - name: faucet
        address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk
        threshold: 500 # Custom threshold for this address
      - name: myAddress
        address: HFFZ1bRayy7ouqVJL2T5g8CitavrmnDCtRQpQnevVx1qoY5
        threshold: 500 # Custom threshold for this address
      - name: whale1
        address: EGP7XztdTosm1EmaATZVMjSWujGEj9nNidhjqA2zZtttkFg
        threshold: 500 # Custom threshold for this address
      - name: whale2
        address: E7ncQKp4xayUoUdpraxBjT7NzLoayLJA4TuPcKKboBkJ5GH
        threshold: 500000 # Custom threshold for this address
      - name: whale3
        address: G7UkJAutjbQyZGRiP8z5bBSBPBJ66JbTKAkFDq3cANwENyX
        threshold: 500 # Custom threshold for this address

kube-prometheus-stack:
  defaultRules:
    create: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: 
        matchLabels:
          release: prometheus-operator
  alertmanager:
    alertmanagerSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: 
        matchLabels:
          release: prometheus-operator

serviceMonitor:
  enabled: true
  labels:
    group: w3f
    release: prometheus-operator

restarter:
  enabled: false
  schedule: "* */6 * * *"
  image:
    repo: web3f/pod-restarter
    tag: v0.1.1

prometheusRules:
  enabled: true
  labels:
    app: w3f
    role: alert-rules
    release: polkadot
  origin: clusterName

resources:
  requests:
    cpu: "50m"
    memory: "100Mi"
