environment: production

image:
  repo: web3f/polkadot-watcher
  tag: v0.1.0

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  matrixbot:
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  subscribe:
    transactions: 
    - name: faucet
      address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk 

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi"
