image:
  repo: web3f/polkadot-watcher-transaction
  #tag: latest

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  environment: production #it is used also to filter the prometheusrules, i.e. to avoid conflicts between production and staging
  matrixbot:
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  subscriber:
    modules:
      balanceBelowThreshold:
        enabled: false
        threshold: 10
      transferEventScanner:
        enabled: true
        #startFromBlock: 10527640 
        sent: true
        received: true
        dataDir: "/app/data"
        scanIntervalMillis: 300000 #5 minutes
        retriesBeforeLeave: 5
        delayBeforeRetryMillis: 5000
    subscriptionsFromGit: #optional
      enabled: false
      targets:
      - platform: GitLab
        private:
          enabled: true
          apiToken: xxx
        network: kusama
        url: https://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main     
    subscriptions: #optional
    - name: faucet
      address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk 

serviceMonitor:
  enabled: false
  labels:
    group: w3f
    release: prometheus-operator

restarter:
  enabled: false
  schedule: "* */6 * * *"
  image:
    repo: web3f/pod-restarter
    tag: v0.1.1


prometheusRules:
  enabled: false
  labels:
    app: w3f
    role: alert-rules #according to https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/alerting.md#prometheusrule-labelling
  origin: clusterName

resources:
  requests:
    cpu: "50m"
    memory: "100Mi"
  #limits:
  #  cpu: "200m"
  #  memory: "300Mi"
