environment: production

image:
  repo: web3f/polkadot-watcher-transaction
  tag: v0.3.0

config:
  endpoint: "wss://kusama-rpc.polkadot.io/"
  port: 3000
  logLevel: info
  matrixbot:
    endpoint: "http://matrixbot:8080/skill/eventmanager/webhook"
  subscriber:
    subscriptions: 
    - name: faucet
      address: EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk 

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    cpu: "600m"
    memory: "500Mi"
