environments:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

- name: watcher-transaction
  chart: ../charts/polkadot-watcher-transaction
  values:
  - ./config/transaction-watcher-values.yaml.gotmpl
